version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  pg:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

  redis:
    image: redis:5
    restart: "always"
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-redispass}
    ports:
      - 6379:6379
    volumes:
      - ./redisdb:/var/lib/redis
    env_file: .env

  celery:
    restart: "always"
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery
    env_file: .env
    command: celery --app=app.celery:app worker -B --loglevel=INFO
    volumes:
      - ./app:/code
    links:
      - redis
      - db
    depends_on:
      - "redis"
      - "db"